### ISSUE TITLE
Suggest project rename

### ISSUE THREAD

**Issue by alerque** [maandree/rq#1]
I don't want to be a spoil sport, but I've run into a problem on my system in that I need to have the binary for the [record query](https://github.com/dflemstr/rq) project on my system as `rq` for interoperability with other programmers. Yes that project came later to the scene and yes they stole this project's short-name. However the project has a lot more traction among Linux programmers in general and has more need for the short name. I don't want to say might makes right here, but at least on my system I'm going to have to rename the read-quickly executable to something else if I want to keep it at all. Rather than just hacking this myself I though I'd at least suggest it might be beneficial to rename the whole project.

While I'm not a regular user, I do play around with this sometimes. Since I don't type it that frequently, when I do it's hard for me to remember what it even was. I find myself asking, "What was the name of that speed reading program?" and searching for it online. Ergo I would make an argument that the fancy short name might actually be hurting this project more than  helping it.

May I suggest `read-quickly` or `quick-read` or something more long and descriptive as the binary and canonical project name?

**Comment by maandree** [comment]
For now you can use set the makefile variable `COMMAND` (e.g. `make COMMAND=read-quickly install`), but I will have to make this permanent. I know, using a two letter name was a bad idea. Since no project could really a dependency on my project, I guess easier for me to change, but I think both projects actually should because of the limited number of available 2-letter names.
